### ISSUE TITLE
TODO List - Décembre

### ISSUE THREAD

**Issue by Uinelj** [bdeecho/Chaudiere#42]
Issue un peu fourre-tout, je suis désolé.

- [x] Envoyer à la vie associative le devis sonolights, histoire que le service électricité puisse se rendre compte de la puissance requise pour l'installation.
- [ ] Booker un rendez-vous entre le service électrique et Gilles, afin qu'ils se rencardent sur les bails électriques. (Un échange de mail ça peut marcher aussi je suppose.
- [x] Faire une demande de licence à la mairie pour le Vendredi 10 Février / Samedi 11 Février.
- [x] Décider de la stratégie de communication au vu des échéances. #43
- [x] Savoir si oui ou non on a une astreinte électrique à prévoir.
- [ ] Recruter du staff pour l'événement et l'installation / désinstallation (10 à 15 personnes)
 
Hésitez pas à __référencer__ les issues qui vous semblent importantes là dedans.

**Comment by AlexFourgs** [comment]
L'astreinte est apparemment bien obligatoire mais pris en charge par la fac / fsdie.

En ce qui concerne le recrutement pour l'instant j'ai 3 ou 4 personnes chaudes en L3 informatique parmis les CMI (les membres de la JE principalement)
